jobs:
- job: macOS
  pool:
    vmImage: macOS-10.13
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - bash: |
      set -e
      sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer
      python -V
      which python
      brew install --verbose Formula/ensmallen.rb
    displayName: build ensmallen

  - bash: |
      brew test --verbose Formula/ensmallen.rb
    displayName: test ensmallen

  - bash: |
      python -m pip install --upgrade pip
      pip install cython numpy
      curl https://kurg.org/misc/brew_mod.py -o brew_mod.py
      python brew_mod.py
      brew install --verbose Formula/mlpack.rb
    displayName: build mlpack


